<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>texttag</name>
   <tag></tag>
   <elementGuidId>f37e982c-1b2f-4610-b57d-4576df9664d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;select2-result-label-16&quot;]/text()</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;select2-result-label-16&quot;]/text()</value>
   </webElementProperties>
</WebElementEntity>
