<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>navtoLayout</name>
   <tag></tag>
   <elementGuidId>c44ab546-bb2c-4550-8cdf-18594366d178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;goLayout&quot;)/i[@class=&quot;layout-icon-lg-grey&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goLayout&quot;)/i[@class=&quot;layout-icon-lg-grey&quot;]</value>
   </webElementProperties>
</WebElementEntity>
