<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Runstill-nextarrow</name>
   <tag></tag>
   <elementGuidId>86c62e50-399d-4e6e-9bf8-60dc3e9ebc29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[(text() = '›' or . = '›')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>›</value>
   </webElementProperties>
</WebElementEntity>
