<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IncludeTexttag</name>
   <tag></tag>
   <elementGuidId>89f876f7-b0d6-450d-8c0f-ec0bfa994866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mCSB_5_container&quot;]/div[2]/div[2]/div[4]/div/label[count(. | //label[@for = 'expTextTagData']) = count(//label[@for = 'expTextTagData'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>expTextTagData</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mCSB_5_container&quot;]/div[2]/div[2]/div[4]/div/label</value>
   </webElementProperties>
</WebElementEntity>
