<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_caret</name>
   <tag></tag>
   <elementGuidId>6c1fa503-4cf9-4c93-b44e-dbbac5e379a6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransforms3d&quot;]/body[1]/div[@class=&quot;wrapper&quot;]/header[1]/nav[@class=&quot;navbar navbar-fixed-top commanHeader&quot;]/div[@class=&quot;container-fluid&quot;]/ul[@class=&quot;nav navbar-nav navbar-right listBtn&quot;]/li[@class=&quot;dropdown profileBox lineRight&quot;]/a[@class=&quot;mainMenu dropdown-toggle&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
</WebElementEntity>
