<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selallduplicateimg</name>
   <tag></tag>
   <elementGuidId>12d647b5-57ef-4ceb-be45-9746239452f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;headerul&quot;)/li[@class=&quot;headerrow&quot;]/span[@class=&quot;colm1&quot;]/div[@class=&quot;chk-div&quot;]/label[@class=&quot;lbl_cls&quot;][count(. | //label[@for = 'selalldupimgs' and @class = 'lbl_cls']) = count(//label[@for = 'selalldupimgs' and @class = 'lbl_cls'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>selalldupimgs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_cls</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerul&quot;)/li[@class=&quot;headerrow&quot;]/span[@class=&quot;colm1&quot;]/div[@class=&quot;chk-div&quot;]/label[@class=&quot;lbl_cls&quot;]</value>
   </webElementProperties>
</WebElementEntity>
