<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selalldupimg</name>
   <tag></tag>
   <elementGuidId>08755ad1-cb3e-4cb6-9e27-8d0170a85cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;headerul&quot;)/li[@class=&quot;headerrow&quot;]/span[@class=&quot;colm1&quot;]/div[@class=&quot;chk-div&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerul&quot;)/li[@class=&quot;headerrow&quot;]/span[@class=&quot;colm1&quot;]/div[@class=&quot;chk-div&quot;]</value>
   </webElementProperties>
</WebElementEntity>
