<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Use Blank_templateDP template</name>
   <tag></tag>
   <elementGuidId>a92057fe-55ac-4238-95da-88692b921645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;user-template-selection&quot;)/div[@class=&quot;col-sm-3 col-md-3 PDCard&quot;]/div[@class=&quot;template-select templateCard&quot;]/img[@class=&quot;templateDP&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-template-selection']/div[2]/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3-ap-southeast-1.amazonaws.com/kanvas.media.mid/cid008/5/kat4_cid008.com/template/3images.png?Signature=XsSaiZ2KZ6I2D2kELBPvqidSOV4%3D&amp;Expires=1554110622&amp;AWSAccessKeyId=AKIAIYXXQPTR5MKSF6VA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dptemplate</name>
      <type>Main</type>
      <value>3images</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>templateDP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-template-selection&quot;)/div[@class=&quot;col-sm-3 col-md-3 PDCard&quot;]/div[@class=&quot;template-select templateCard&quot;]/img[@class=&quot;templateDP&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='user-template-selection']/div[2]/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Blank'])[1]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Templates'])[1]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='del (PPT)'])[1]/preceding::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dell1 (PPT)'])[1]/preceding::img[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <value>//img[contains(@src,'https://s3-ap-southeast-1.amazonaws.com/kanvas.media.mid/cid008/5/kat4_cid008.com/template/3images.png?Signature=XsSaiZ2KZ6I2D2kELBPvqidSOV4%3D&amp;Expires=1554110622&amp;AWSAccessKeyId=AKIAIYXXQPTR5MKSF6VA')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
