<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loadtemp-imagemodes</name>
   <tag></tag>
   <elementGuidId>017c9dae-3fa8-48ab-9988-2ac044ea046c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src = 'https://s3-ap-southeast-1.amazonaws.com/kanvas.media.mid/cid008/5/kat64_cid008.com/template/imagemodes.png?Signature=z6b1N6ufEMTPB1Qi%2Fo83MVMKBOE%3D&amp;Expires=1571377243&amp;AWSAccessKeyId=AKIAIYXXQPTR5MKSF6VA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3-ap-southeast-1.amazonaws.com/kanvas.media.mid/cid008/5/kat64_cid008.com/template/imagemodes.png?Signature=z6b1N6ufEMTPB1Qi%2Fo83MVMKBOE%3D&amp;Expires=1571377243&amp;AWSAccessKeyId=AKIAIYXXQPTR5MKSF6VA</value>
   </webElementProperties>
</WebElementEntity>
