<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loadtemp-PPTXtemp</name>
   <tag></tag>
   <elementGuidId>e3fb91e9-73dc-468f-b88d-4e8ce5ab6079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src = 'https://s3-ap-southeast-1.amazonaws.com/kanvas.media.mid/cid008/5/kat64_cid008.com/template/PPTXtemp.png?Signature=7Pn9DydpxqlvaT3uubhAcyc%2F6Es%3D&amp;Expires=1571397906&amp;AWSAccessKeyId=AKIAIYXXQPTR5MKSF6VA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3-ap-southeast-1.amazonaws.com/kanvas.media.mid/cid008/5/kat64_cid008.com/template/PPTXtemp.png?Signature=7Pn9DydpxqlvaT3uubhAcyc%2F6Es%3D&amp;Expires=1571397906&amp;AWSAccessKeyId=AKIAIYXXQPTR5MKSF6VA</value>
   </webElementProperties>
</WebElementEntity>
